### ISSUE TITLE
Unable to get get "THE FAMA AND FRENCH FACTORS FOR THE SWEDISH MARKET"

### ISSUE THREAD

**Issue by JoachimSm** [SwedishHouseofFinance/SHoF-Platform-Issue-Tracker#1]
Hi,
When I click "Get the dataset", it simply returns "An error occourred, try again later"

Hope someone can help me get access to this data.

Best regards,
Joachim

**Comment by CarminePalombo** [comment]
Hi Joachim,

sometimes the archive was regenerated and therefore unavailable during those periods.
I changed this behaviour, shouldn't happen again.

Thanks for the report.

**Comment by JoachimSm** [comment]
Hi Carmine,

I still get the same error. After the "Email verification successful", I proceed with "Go back to the SHoF website and download the file. and press Download file. I am the redirected to https://data.houseoffinance.se/otherDB/famaFrench and I can press "Get the dataset" . I am then redirected to https://data.houseoffinance.se/otherDB/download?folder=famaFrench&file=famaFrench.zip  and "An error occourred, try again later". Hope you can help me with this issue.

Best regards,
Joachim

**Comment by CarminePalombo** [comment]
Hi Joachim,

Just tried and it works flawlessly. The authentication process relies on cookies, are they allowed in your browser?
Carmine Palombo
Swedish House of Finance
Research Data Centre

**Comment by JoachimSm** [comment]
Hi Carmine,

I have tried the process with Google Chrome, Internet Explorer and Firefox. Still get an error.  The authentication process appears to work, but when I press the download file from the email, and I am redirected to "https://data.houseoffinance.se/otherDB/download?folder=famaFrench&file=famaFrench.zip" it fails for all the browsers.

Best regards,
Joachim
